#!/usr/bin/env python
#coding:utf-8
#refer: /usr/lib/python2.7/json/tool.py
#$ cat /dev/stdin | python -m json.tool
import sys
import json

def main():
    if len(sys.argv) == 1:
        infile = sys.stdin
        outfile = sys.stdout
    elif len(sys.argv) == 2:
        infile = open(sys.argv[1], 'rb')
        outfile = sys.stdout
    elif len(sys.argv) == 3:
        infile = open(sys.argv[1], 'rb')
        outfile = open(sys.argv[2], 'wb')
    else:
        raise SystemExit(sys.argv[0] + " [infile [outfile]]")
    try:
        obj = json.load(infile)
    except ValueError, e:
        raise SystemExit(e)
    json.dump(obj, outfile, ensure_ascii=False, sort_keys=True, indent=4)
    outfile.write('\n')


if __name__ == '__main__':
    reload(sys)
    sys.setdefaultencoding('utf8')
    main()
